### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I took a look at the code and have a few suggestions for changes. There are quite a few, which certainly makes it difficult to understand. Sorry. But I have created a next-episode account and tested it.

Let me know if you have any questions.

It's a nice module. Thanks for that!

Changes:

- Move screenshots into repository
- Replace request by internal fetch
- Optimize installation process
- Format files
- Lint JavaSript files
- Add .gitignore
- Change console.log to Log.log
- Fix license field and description in package.json

### CODE REVIEW

**Review by PierreGode — APPROVED** [review]
Thank you for a good commit.

**Comment by KristjanESPERANTO** [comment]
You're welcome! :slightly_smiling_face: 

I saw you  added this:

```
npm install request
npm install qrcode
npm install uuid
```

1. Since my changes `request` isn't necessary anymore.
2. The two dependencies `qrcode` and `uuid` are now in the `package.json` so they will be installed by `npm install`. Manual installation isn't necessary anymore.

You can of course still list the dependencies. Maybe just like this:

> The following external packages are used for this module:
> 1. `qrcode` - to create the QR code for the setup.
> 2. `uuid` - to do ... 

**Something else**: Unfortunately, I chose the file name of the QR code screenshot unfavorably. This screenshot is now used in the [module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) 😅, which is of course not ideal. I suggest to rename the screenshot to screenshotqrcode.png.

**Comment by PierreGode** [comment]
Thank you.No it was me missing the you had added them there.Ok i have renamed the qr code image.Awesome page the module list page. Best regards /Pierre Gode8 jan. 2024 kl. 01:02 skrev Kristjan ESPERANTO ***@***.***>:﻿
You're welcome! 🙂
I saw you  added this:
npm install request
npm install qrcode
npm install uuid


Since my changes request isn't necessary anymore.
The two dependencies qrcode and uuid are now in the package.json so they will be installed by npm install. Manual installation isn't necessary anymore.

You can of course still list the dependencies. Maybe just just like this:

The following external packages are used for this module:

qrcode - to create the QR code for the setup.
uuid - to do ...


Something else: Unfortunately, I chose the file name of the QR code screenshot unfavorably. This screenshot is now used in the module list 😅, which is of course not ideal. I suggest to rename the screenshot to screenshotqrcode.png.

**Comment by KristjanESPERANTO** [comment]
Okay, great. Now your module is displayed perfectly!

**Pull request merged**
